/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessRegistrySol from "./AccessRegistry.sol";
export type { accessRegistrySol };
import type * as hashCastGatewaySol from "./HashCastGateway.sol";
export type { hashCastGatewaySol };
import type * as hashCastKarmaSol from "./HashCastKarma.sol";
export type { hashCastKarmaSol };
import type * as testEd25519Sol from "./TestEd25519.sol";
export type { testEd25519Sol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
