/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessRegistry } from "./AccessRegistry";
export type { IERC20 } from "./IERC20";
export type { IEd25519Lib } from "./IEd25519Lib";
export type { IEddsaValidationModule } from "./IEddsaValidationModule";
